language: php

php:
  - '5.6.4'
  - '7.0'
  - '7.1'

env:
  - ILLUMINATE_VERSION=5.3.*

matrix:
  include:
    - php: 5.6.4
      env: ILLUMINATE_VERSION=5.3.*
    - php: 5.6.4
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*

before_install:
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "illuminate/events:${ILLUMINATE_VERSION}" --no-update -v

install: composer update --prefer-source --no-interaction --dev -v

script: vendor/bin/phpunit --debug -c phpunit.xml --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
